export interface Product {
  id: number
  name: string
  price: number
  originalPrice?: number
  image: string
  rating: number
  reviews: number
  category: string
  isNew?: boolean
  isSale?: boolean
  description: string
  features: string[]
  inStock: boolean
}

export const products: Product[] = [
  {
    id: 1,
    name: "Premium Wireless Headphones",
    price: 299,
    originalPrice: 399,
    image: "/premium-wireless-headphones.png",
    rating: 4.8,
    reviews: 124,
    category: "Electronics",
    isNew: true,
    isSale: true,
    description:
      "Experience crystal-clear audio with our premium wireless headphones featuring active noise cancellation and 30-hour battery life.",
    features: ["Active Noise Cancellation", "30-hour Battery", "Bluetooth 5.0", "Quick Charge"],
    inStock: true,
  },
  {
    id: 2,
    name: "Luxury Smartwatch",
    price: 599,
    image: "/placeholder-tpfme.png",
    rating: 4.9,
    reviews: 89,
    category: "Electronics",
    isNew: true,
    description:
      "Stay connected and track your fitness with this premium smartwatch featuring health monitoring and GPS.",
    features: ["Heart Rate Monitor", "GPS Tracking", "Water Resistant", "7-day Battery"],
    inStock: true,
  },
  {
    id: 3,
    name: "Designer Laptop Bag",
    price: 149,
    originalPrice: 199,
    image: "/designer-laptop-bag.png",
    rating: 4.7,
    reviews: 156,
    category: "Accessories",
    isSale: true,
    description: "Protect your laptop in style with this premium leather laptop bag designed for professionals.",
    features: ["Genuine Leather", "Padded Compartment", "Multiple Pockets", "Adjustable Strap"],
    inStock: true,
  },
  {
    id: 4,
    name: "Professional Camera",
    price: 1299,
    image: "/professional-camera.png",
    rating: 4.9,
    reviews: 67,
    category: "Electronics",
    description:
      "Capture stunning photos with this professional-grade camera featuring advanced autofocus and 4K video recording.",
    features: ["24MP Sensor", "4K Video", "Advanced Autofocus", "Weather Sealed"],
    inStock: true,
  },
  {
    id: 5,
    name: "Ergonomic Office Chair",
    price: 449,
    originalPrice: 549,
    image: "/ergonomic-office-chair.png",
    rating: 4.6,
    reviews: 203,
    category: "Furniture",
    isSale: true,
    description:
      "Work comfortably all day with this ergonomic office chair featuring lumbar support and adjustable height.",
    features: ["Lumbar Support", "Adjustable Height", "Breathable Mesh", "360° Swivel"],
    inStock: true,
  },
  {
    id: 6,
    name: "Smart Home Hub",
    price: 199,
    image: "/smart-home-hub.png",
    rating: 4.8,
    reviews: 91,
    category: "Electronics",
    description: "Control your entire smart home with this advanced hub supporting all major smart home protocols.",
    features: ["Voice Control", "App Integration", "Multiple Protocols", "Easy Setup"],
    inStock: true,
  },
  {
    id: 7,
    name: "Luxury Leather Wallet",
    price: 89,
    image: "/luxury-leather-wallet.png",
    rating: 4.6,
    reviews: 89,
    category: "Accessories",
    description: "Carry your essentials in style with this handcrafted leather wallet featuring RFID protection.",
    features: ["RFID Protection", "Genuine Leather", "Multiple Card Slots", "Coin Pocket"],
    inStock: true,
  },
  {
    id: 8,
    name: "Smart Fitness Watch",
    price: 249,
    image: "/smart-fitness-watch.png",
    rating: 4.7,
    reviews: 156,
    category: "Electronics",
    isNew: true,
    description: "Track your fitness goals with this advanced fitness watch featuring GPS and health monitoring.",
    features: ["GPS Tracking", "Heart Rate Monitor", "Sleep Tracking", "Water Resistant"],
    inStock: true,
  },
  {
    id: 9,
    name: "Designer Sunglasses",
    price: 159,
    originalPrice: 199,
    image: "/designer-sunglasses.png",
    rating: 4.5,
    reviews: 67,
    category: "Accessories",
    isSale: true,
    description: "Protect your eyes in style with these premium designer sunglasses featuring UV protection.",
    features: ["UV Protection", "Polarized Lenses", "Lightweight Frame", "Scratch Resistant"],
    inStock: true,
  },
  {
    id: 10,
    name: "Organic Cotton T-Shirt",
    price: 39,
    image: "/organic-cotton-tshirt.png",
    rating: 4.4,
    reviews: 203,
    category: "Clothing",
    description: "Stay comfortable and eco-friendly with this premium organic cotton t-shirt.",
    features: ["100% Organic Cotton", "Soft Feel", "Breathable", "Machine Washable"],
    inStock: true,
  },
  {
    id: 11,
    name: "Bluetooth Speaker",
    price: 79,
    image: "/bluetooth-speaker.png",
    rating: 4.6,
    reviews: 91,
    category: "Electronics",
    description: "Enjoy high-quality audio anywhere with this portable Bluetooth speaker featuring 360° sound.",
    features: ["360° Sound", "12-hour Battery", "Water Resistant", "Voice Assistant"],
    inStock: true,
  },
  {
    id: 12,
    name: "Minimalist Backpack",
    price: 119,
    image: "/minimalist-backpack.png",
    rating: 4.8,
    reviews: 145,
    category: "Accessories",
    isNew: true,
    description: "Carry your essentials in style with this minimalist backpack featuring laptop compartment.",
    features: ["Laptop Compartment", "Water Resistant", "Multiple Pockets", "Comfortable Straps"],
    inStock: true,
  },
  {
    id: 13,
    name: "Ceramic Coffee Mug",
    price: 24,
    image: "/ceramic-coffee-mug.png",
    rating: 4.3,
    reviews: 78,
    category: "Home",
    description: "Start your day right with this premium ceramic coffee mug featuring heat retention technology.",
    features: ["Heat Retention", "Dishwasher Safe", "Comfortable Handle", "12oz Capacity"],
    inStock: true,
  },
  {
    id: 14,
    name: "Wireless Charging Pad",
    price: 49,
    image: "/wireless-charging-pad.png",
    rating: 4.5,
    reviews: 112,
    category: "Electronics",
    description: "Charge your devices wirelessly with this fast-charging pad compatible with all Qi-enabled devices.",
    features: ["Fast Charging", "Qi Compatible", "LED Indicator", "Non-slip Base"],
    inStock: true,
  },
  {
    id: 15,
    name: "Premium Yoga Mat",
    price: 89,
    image: "/premium-yoga-mat.png",
    rating: 4.7,
    reviews: 134,
    category: "Fitness",
    description: "Practice yoga comfortably with this premium non-slip yoga mat made from eco-friendly materials.",
    features: ["Non-slip Surface", "Eco-friendly", "Extra Thick", "Carrying Strap"],
    inStock: true,
  },
  {
    id: 16,
    name: "Stainless Steel Water Bottle",
    price: 34,
    image: "/stainless-steel-bottle.png",
    rating: 4.6,
    reviews: 89,
    category: "Home",
    description: "Stay hydrated with this insulated stainless steel water bottle that keeps drinks cold for 24 hours.",
    features: ["24-hour Cold", "BPA Free", "Leak Proof", "Wide Mouth"],
    inStock: true,
  },
  {
    id: 17,
    name: "Gaming Mechanical Keyboard",
    price: 159,
    originalPrice: 199,
    image: "/gaming-mechanical-keyboard.png",
    rating: 4.8,
    reviews: 167,
    category: "Electronics",
    isSale: true,
    description: "Enhance your gaming experience with this mechanical keyboard featuring RGB backlighting.",
    features: ["Mechanical Switches", "RGB Backlighting", "Programmable Keys", "Anti-ghosting"],
    inStock: true,
  },
  {
    id: 18,
    name: "Silk Pillowcase",
    price: 59,
    image: "/silk-pillowcase.png",
    rating: 4.5,
    reviews: 98,
    category: "Home",
    description: "Sleep better with this luxurious silk pillowcase that's gentle on skin and hair.",
    features: ["100% Mulberry Silk", "Hypoallergenic", "Temperature Regulating", "Machine Washable"],
    inStock: true,
  },
  {
    id: 19,
    name: "Portable Phone Stand",
    price: 19,
    image: "/placeholder-dwwfp.png",
    rating: 4.4,
    reviews: 156,
    category: "Accessories",
    description: "Keep your phone at the perfect angle with this adjustable and portable phone stand.",
    features: ["Adjustable Angle", "Foldable Design", "Non-slip Base", "Universal Compatibility"],
    inStock: true,
  },
  {
    id: 20,
    name: "Essential Oil Diffuser",
    price: 69,
    image: "/essential-oil-diffuser.png",
    rating: 4.6,
    reviews: 123,
    category: "Home",
    description: "Create a relaxing atmosphere with this ultrasonic essential oil diffuser featuring LED lighting.",
    features: ["Ultrasonic Technology", "LED Lighting", "Timer Function", "Auto Shut-off"],
    inStock: true,
  },
  {
    id: 21,
    name: "Wireless Gaming Mouse",
    price: 89,
    image: "/wireless-gaming-mouse.png",
    rating: 4.7,
    reviews: 145,
    category: "Electronics",
    description: "Dominate your games with this high-precision wireless gaming mouse featuring customizable buttons.",
    features: ["High DPI Sensor", "Customizable Buttons", "RGB Lighting", "Long Battery Life"],
    inStock: true,
  },
  {
    id: 22,
    name: "Bamboo Cutting Board",
    price: 45,
    image: "/bamboo-cutting-board.png",
    rating: 4.5,
    reviews: 87,
    category: "Home",
    description: "Prepare meals safely with this eco-friendly bamboo cutting board featuring juice grooves.",
    features: ["Eco-friendly Bamboo", "Juice Grooves", "Knife-friendly", "Easy to Clean"],
    inStock: true,
  },
  {
    id: 23,
    name: "Fitness Resistance Bands",
    price: 29,
    image: "/placeholder-g5gtj.png",
    rating: 4.4,
    reviews: 178,
    category: "Fitness",
    description: "Get a full-body workout anywhere with this set of resistance bands in multiple resistance levels.",
    features: ["Multiple Resistance Levels", "Portable", "Durable Material", "Exercise Guide Included"],
    inStock: true,
  },
  {
    id: 24,
    name: "LED Desk Lamp",
    price: 79,
    image: "/led-desk-lamp.png",
    rating: 4.6,
    reviews: 134,
    category: "Home",
    description: "Illuminate your workspace with this adjustable LED desk lamp featuring multiple brightness levels.",
    features: ["Adjustable Brightness", "Touch Control", "USB Charging Port", "Eye-care Technology"],
    inStock: true,
  },
  {
    id: 25,
    name: "Insulated Lunch Box",
    price: 39,
    image: "/placeholder-uq798.png",
    rating: 4.3,
    reviews: 92,
    category: "Home",
    description: "Keep your meals fresh with this insulated lunch box featuring multiple compartments.",
    features: ["Insulated Design", "Multiple Compartments", "Easy to Clean", "Leak-proof"],
    inStock: true,
  },
]

export function getProductById(id: number): Product | undefined {
  return products.find((product) => product.id === id)
}

export function getProductsByCategory(category: string): Product[] {
  if (category === "all") return products
  return products.filter((product) => product.category === category)
}

export function getFeaturedProducts(count = 10): Product[] {
  return products.slice(0, count)
}
